keys:
  - &mixos_aj01_age age1phla80tww0rnfgju60l86u8jwcld9gzlkx3x9nghc7lwedm2q4lq4m747w
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *mixos_aj01_age
  - path_regex: secrets/mixos/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *mixos_aj01_age
